export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";

export const FETCH_TVSHOWS = "FETCH_TVSHOWS";
export const FETCH_TVSHOWS_SUCCESS = "FETCH_TVSHOWS_SUCCESS";
export const FETCH_TVSHOWS_FAIL = "FETCH_TVSHOWS_FAIL";

export const SEARCH_ALL = "SEARCH_ALL";
export const SEARCH_ALL_SUCCESS = "SEARCH_ALL_SUCCESS";
export const SEARCH_ALL_FAIL = "SEARCH_ALL_FAIL";

export const GET_SINGLE = "GET_SINGLE";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const GET_SINGLE_FAIL = "GET_SINGLE_FAIL";

